name: CI Badges
on:
  push:
    branches:
      - main

env:
  GIST_ID: ${{ secrets.GIST_ID }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run test:coverage
        env:
          GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
      - run: npm run build
      - run: sed -i '0,/index.js/s//dist\/index.js/' action.yml package.json
      - uses: ./
        with:
          gist-id: ${{ env.GIST_ID }}
          token: ${{ secrets.GIST_TOKEN }}
